#!/usr/bin/env python3
"""
ZORIXEL AIOS Auto-Evolution & Roast Gate Injector
Scans all 60+ skills in d:\AI-OS\.agents\skills and embeds the standardized
Post-Execution Auto-Evolution & Adversarial /roast Gate in every SKILL.md.
"""

import os
import sys

WORKSPACE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKILLS_DIR = os.path.join(WORKSPACE_ROOT, ".agents", "skills")

ROAST_GATE_BLOCK = """

---

## 🔄 Post-Execution Auto-Evolution & Adversarial `/roast` Gate

At the completion of every execution of this skill:

1. **Adversarial `/roast` Council Review**: Convene the 5-Persona ZORIXEL AIOS Roast Council (`/roast`) to stress-test the output, code edits, or strategy generated by this skill. Red-team for missing edge cases, terminal shell bugs, token leaks, or optimization gaps.
2. **Autonomous Tool, Script & Skill Auto-Upgrade Loop**:
   - If new error patterns or execution safeguards are discovered, append them to `references/GLOBAL_ERROR_PREVENTION_RULES.md` and execute `python scripts/sync_global_rules.py` via `run_command` so system prompts (`AGENTS.md` and `GEMINI.md`) auto-update inline.
   - Run pre-flight health checks (`aios_gws_health_check.py`, `test_notion_formula.py`, `graphify_runner.py`).
   - Self-upgrade this `SKILL.md` instruction file with newly learned edge cases using `replace_file_content` or `write_to_file`.
3. **Register & Log**: Log milestone upgrades in [WORKSPACE_MAP.md](file:///d:/AI-OS/WORKSPACE_MAP.md) and [decisions/log.md](file:///d:/AI-OS/decisions/log.md).
"""

def process_skill(skill_folder_path):
    skill_md_path = os.path.join(skill_folder_path, "SKILL.md")
    if not os.path.exists(skill_md_path):
        return False
        
    with open(skill_md_path, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()
        
    if "## 🔄 Post-Execution Auto-Evolution & Adversarial `/roast` Gate" in content:
        print(f"[SKIP] {os.path.basename(skill_folder_path)} already contains auto-evolution gate.")
        return True
        
    new_content = content.rstrip() + ROAST_GATE_BLOCK + "\n"
    
    with open(skill_md_path, "w", encoding="utf-8") as f:
        f.write(new_content)
        
    print(f"[UPDATED] Injected Auto-Evolution & Roast Gate into: {skill_md_path}")
    return True

def main():
    print("========================================================")
    print("ZORIXEL AIOS: Skill Auto-Evolution & Roast Gate Injector")
    print("========================================================\n")
    
    if not os.path.exists(SKILLS_DIR):
        print(f"[ERROR] Skills directory not found: {SKILLS_DIR}")
        sys.exit(1)
        
    skill_folders = [os.path.join(SKILLS_DIR, d) for d in os.listdir(SKILLS_DIR) if os.path.isdir(os.path.join(SKILLS_DIR, d))]
    
    updated_count = 0
    total_count = len(skill_folders)
    
    for folder in skill_folders:
        if process_skill(folder):
            updated_count += 1
            
    print(f"\n========================================================")
    print(f"SKILL INJECTION COMPLETE! {updated_count}/{total_count} skills updated.")
    print("========================================================\n")

if __name__ == "__main__":
    main()
